export interface Odai {
  char: string;
  strokes: number;
}

export const ODAI_LIST: Odai[] = [
  { char: "あ", strokes: 3 },
  { char: "い", strokes: 2 },
  { char: "う", strokes: 2 },
  { char: "え", strokes: 2 },
  { char: "お", strokes: 3 },
  { char: "か", strokes: 3 },
  { char: "き", strokes: 4 },
  { char: "く", strokes: 1 },
  { char: "け", strokes: 3 },
  { char: "こ", strokes: 2 },
  { char: "さ", strokes: 3 },
  { char: "し", strokes: 1 },
  { char: "す", strokes: 2 },
  { char: "せ", strokes: 3 },
  { char: "そ", strokes: 1 },
  { char: "た", strokes: 4 },
  { char: "ち", strokes: 2 },
  { char: "つ", strokes: 1 },
  { char: "て", strokes: 1 },
  { char: "と", strokes: 2 },
  { char: "な", strokes: 4 },
  { char: "に", strokes: 3 },
  { char: "ぬ", strokes: 2 },
  { char: "ね", strokes: 2 },
  { char: "の", strokes: 1 },
  { char: "は", strokes: 3 },
  { char: "ひ", strokes: 1 },
  { char: "ふ", strokes: 4 },
  { char: "へ", strokes: 1 },
  { char: "ほ", strokes: 4 },
  { char: "ま", strokes: 3 },
  { char: "み", strokes: 2 },
  { char: "む", strokes: 3 },
  { char: "め", strokes: 2 },
  { char: "も", strokes: 3 },
  { char: "や", strokes: 3 },
  { char: "ゆ", strokes: 2 },
  { char: "よ", strokes: 2 },
  { char: "ら", strokes: 2 },
  { char: "り", strokes: 2 },
  { char: "る", strokes: 1 },
  { char: "れ", strokes: 2 },
  { char: "ろ", strokes: 1 },
  { char: "わ", strokes: 2 },
  { char: "を", strokes: 3 },
  { char: "ん", strokes: 1 }
];
